import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../domain/entities/debt_settlement.dart';
import '../../domain/entities/group.dart';
import '../../domain/entities/group_member.dart';
import '../../domain/entities/group_split.dart';
import '../../domain/entities/member_balance.dart';
import '../../domain/services/debt_settlement_calculator.dart';
import '../../domain/services/group_balance_calculator.dart';

final class GroupPdfReportService {
  const GroupPdfReportService();

  static const GroupBalanceCalculator _balanceCalculator =
      GroupBalanceCalculator();

  static const DebtSettlementCalculator _settlementCalculator =
      DebtSettlementCalculator();

  Future<Uint8List> buildReport({
    required Group group,
    required List<GroupSplit> splits,
  }) async {
    final List<String> memberIds = group.members
        .map((GroupMember member) => member.id)
        .toList(growable: false);

    final List<MemberBalance> balances = _balanceCalculator.calculate(
      memberIds: memberIds,
      splits: splits,
    );

    final List<DebtSettlement> settlements = _settlementCalculator.calculate(
      balances,
    );

    final pw.Document document = pw.Document();

    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return <pw.Widget>[
            pw.Text(
              group.name,
              style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              'Group Expense Report',
              style: const pw.TextStyle(fontSize: 14),
            ),
            pw.SizedBox(height: 6),
            pw.Text('Currency: ${group.defaultCurrencyCode}'),
            pw.Text('Members: ${group.members.length}'),
            pw.SizedBox(height: 24),

            _heading('Members'),
            pw.SizedBox(height: 8),
            _membersTable(group),

            pw.SizedBox(height: 24),

            _heading('Expenses'),
            pw.SizedBox(height: 8),

            if (splits.isEmpty)
              pw.Text('No group expenses recorded.')
            else
              _expensesTable(group: group, splits: splits),

            pw.SizedBox(height: 24),

            _heading('Net Balances'),
            pw.SizedBox(height: 8),
            _balancesTable(group: group, balances: balances),

            pw.SizedBox(height: 24),

            _heading('Settlement Suggestions'),
            pw.SizedBox(height: 8),

            if (settlements.isEmpty)
              pw.Text('Everyone is settled.')
            else
              _settlementsTable(group: group, settlements: settlements),

            pw.SizedBox(height: 24),
            pw.Divider(),

            pw.Text(
              'Generated by Splitwise Expense Tracker',
              style: const pw.TextStyle(fontSize: 9),
            ),
          ];
        },
      ),
    );

    return document.save();
  }

  pw.Widget _heading(String text) {
    return pw.Text(
      text,
      style: pw.TextStyle(fontSize: 17, fontWeight: pw.FontWeight.bold),
    );
  }

  pw.Widget _membersTable(Group group) {
    return _table(
      headers: const <String>['Member', 'Email'],
      rows: group.members
          .map(
            (GroupMember member) => <String>[
              member.isCurrentUser
                  ? '${member.displayName} (You)'
                  : member.displayName,
              member.email ?? '-',
            ],
          )
          .toList(growable: false),
    );
  }

  pw.Widget _expensesTable({
    required Group group,
    required List<GroupSplit> splits,
  }) {
    return _table(
      headers: const <String>[
        'Expense',
        'Paid By',
        'Amount',
        'Participants',
        'Date',
      ],
      rows: splits
          .where((GroupSplit split) => !split.isDeleted)
          .map((GroupSplit split) {
            final GroupMember? payer = _findMember(group, split.paidByMemberId);

            return <String>[
              split.title,
              payer?.displayName ?? 'Unknown',
              '${split.currencyCode} '
                  '${_formatMinorAmount(split.totalAmountMinor, split.currencyScale)}',
              '${split.shares.length}',
              _formatDate(split.occurredAt),
            ];
          })
          .toList(growable: false),
    );
  }

  pw.Widget _balancesTable({
    required Group group,
    required List<MemberBalance> balances,
  }) {
    return _table(
      headers: const <String>['Member', 'Status', 'Amount'],
      rows: balances
          .map((MemberBalance balance) {
            final GroupMember? member = _findMember(group, balance.memberId);

            final String status;

            if (balance.balanceMinor > 0) {
              status = 'Is owed';
            } else if (balance.balanceMinor < 0) {
              status = 'Owes';
            } else {
              status = 'Settled';
            }

            return <String>[
              member?.displayName ?? 'Unknown',
              status,
              balance.balanceMinor == 0
                  ? '-'
                  : '${group.defaultCurrencyCode} '
                        '${_formatMinorAmount(balance.balanceMinor.abs(), group.defaultCurrencyScale)}',
            ];
          })
          .toList(growable: false),
    );
  }

  pw.Widget _settlementsTable({
    required Group group,
    required List<DebtSettlement> settlements,
  }) {
    return _table(
      headers: const <String>['From', 'To', 'Amount'],
      rows: settlements
          .map((DebtSettlement settlement) {
            final GroupMember? from = _findMember(
              group,
              settlement.fromMemberId,
            );

            final GroupMember? to = _findMember(group, settlement.toMemberId);

            return <String>[
              from?.displayName ?? 'Unknown',
              to?.displayName ?? 'Unknown',
              '${group.defaultCurrencyCode} '
                  '${_formatMinorAmount(settlement.amountMinor, group.defaultCurrencyScale)}',
            ];
          })
          .toList(growable: false),
    );
  }

  pw.Widget _table({
    required List<String> headers,
    required List<List<String>> rows,
  }) {
    final List<pw.TableRow> tableRows = <pw.TableRow>[
      pw.TableRow(
        children: headers
            .map((String header) => _cell(header, bold: true))
            .toList(growable: false),
      ),
      ...rows.map(
        (List<String> row) => pw.TableRow(
          children: row
              .map((String value) => _cell(value))
              .toList(growable: false),
        ),
      ),
    ];

    return pw.Table(
      border: pw.TableBorder.all(width: 0.5),
      children: tableRows,
    );
  }

  pw.Widget _cell(String text, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 9,
          fontWeight: bold ? pw.FontWeight.bold : null,
        ),
      ),
    );
  }

  GroupMember? _findMember(Group group, String memberId) {
    for (final GroupMember member in group.members) {
      if (member.id == memberId) {
        return member;
      }
    }

    return null;
  }

  String _formatMinorAmount(int amountMinor, int scale) {
    final int absoluteAmount = amountMinor.abs();

    int divisor = 1;

    for (int index = 0; index < scale; index++) {
      divisor *= 10;
    }

    final int whole = absoluteAmount ~/ divisor;

    if (scale == 0) {
      return whole.toString();
    }

    final int fraction = absoluteAmount % divisor;

    return '$whole.'
        '${fraction.toString().padLeft(scale, '0')}';
  }

  String _formatDate(DateTime date) {
    final DateTime local = date.toLocal();

    return '${local.day.toString().padLeft(2, '0')}/'
        '${local.month.toString().padLeft(2, '0')}/'
        '${local.year}';
  }
}
